- name: Enable php74 and epel repositories
  yum: name=amazon-cloudwatch-agent update_cache=yes state=latest

- name: Set amazon-cloudwatch-agent config
  template:
    src: "files/cloudwatch-agent-config.json"
    dest: "/opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.d/file_config.json"
    owner: root
    group: root
    mode: u=rw,g=rw,o=r

- name: Start amazon-cloudwatch-agent
  shell: /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a fetch-config -m ec2 -s -c file:/opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.d/file_config.json


  