- name: Disable PHP 7.2
  shell: amazon-linux-extras disable php7.2

- name: Enable PHP 8.0
  shell: amazon-linux-extras enable php8.0

- name: Clean yum metadata
  shell: yum clean metadata

- name: Install PHP 8.0
  shell: amazon-linux-extras install -y php8.0

- name : Install recommended php modules for Wordpress
  yum: name={{ item }} update_cache=yes state=latest
  loop: "{{ php_modules }}"

- name: Update mariadb socket location in php.ini
  lineinfile:
    dest: "/etc/php.ini"
    regexp: "mysqli.default_socket ="
    line: "mysqli.default_socket = /ebs/mysql/mysql.sock"