- name: Install PHP
  shell: amazon-linux-extras install -y php7.2

- name : Install recommended php modules for Wordpress
  yum: name={{ item }} update_cache=yes state=latest
  loop: "{{ php_modules }}"

- name: Update mariadb socket location in php.ini
  lineinfile:
    dest: "/etc/php.ini"
    regexp: "mysqli.default_socket ="
    line: "mysqli.default_socket = /ebs/mysql/mysql.sock"